spring:
  datasource:
    sso:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456song
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.persist.sso: debug
  file: log/blog-dev.log



